[Package]
Name="texas_instruments_lib_n33xx"
Version="1.0.0.1"
Release=""
ID=e7150b3359c2bbdf85cd115c3e7847e7
File Format="vip"
Format Version="2010"
Display Name="N33XX"


[Description]
Description=""
Summary=""
License=""
Copyright="Copyright (c) 2013, Texas Instruments"
Distribution=""
Vendor="Texas Instruments"
URL=""
Packager="AnandkumarSP"
Demo="FALSE"
Release Notes=""
System Package="FALSE"


[Platform]
Exclusive_LabVIEW_Version=">=10.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires=""
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="2"
Sub-Packages=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=138
File 0="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/N33XX.lvlib"
File 1="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/N33XX.lvproj"
File 2="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/N33XX.xml"
File 3="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/N33XX Close.vi"
File 4="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/N33XX Initialize.vi"
File 5="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/N33XX VI Tree.vi"
File 6="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Utility/N33XX Error Query.vi"
File 7="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Utility/N33XX Get Firmware Revision.vi"
File 8="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Utility/N33XX IDN Query.vi"
File 9="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Utility/N33XX Reset.vi"
File 10="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Utility/N33XX Self Test.vi"
File 11="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Current List.ctl"
File 12="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Current Parameters.ctl"
File 13="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Current Protection Parameters.ctl"
File 14="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Digital Port1.ctl"
File 15="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX List Parameters.ctl"
File 16="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Measured Current.ctl"
File 17="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Measured Power.ctl"
File 18="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Measured Voltage.ctl"
File 19="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Regulation Mode.ctl"
File 20="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Regulator.ctl"
File 21="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Resistance List.ctl"
File 22="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Resistance Parameters.ctl"
File 23="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Serial Configuration.ctl"
File 24="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Slew Rate List.ctl"
File 25="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Slew Rate Parameters.ctl"
File 26="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Sweep Parameters.ctl"
File 27="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Transient List.ctl"
File 28="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Transient Parameters.ctl"
File 29="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Transient Slew Rate List.ctl"
File 30="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Transient Slew Rate.ctl"
File 31="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Trigger Parameters.ctl"
File 32="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Voltage List.ctl"
File 33="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Typedefs/N33XX Voltage Parameters.ctl"
File 34="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Example/N33XX Getting Started with Current List.vi"
File 35="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Example/N33XX Getting Started with Resistance List.vi"
File 36="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Example/N33XX Getting Started with Resistance.vi"
File 37="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Example/N33XX Getting Started with Voltage List.vi"
File 38="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Channel Status.vi"
File 39="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Current.vi"
File 40="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Instantaneous Current.vi"
File 41="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Instantaneous Power.vi"
File 42="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Instantaneous Voltage.vi"
File 43="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Power.vi"
File 44="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement Voltage.vi"
File 45="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/N33XX Read Measurement.vi"
File 46="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Current.vi"
File 47="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Instantaneous Current.vi"
File 48="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Instantaneous Power.vi"
File 49="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Instantaneous Voltage.vi"
File 50="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Power.vi"
File 51="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Data/Low Level/N33XX Get Measurement Voltage.vi"
File 52="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Channel.vi"
File 53="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Current List.vi"
File 54="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Current Protection.vi"
File 55="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Current.vi"
File 56="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Digital Port.vi"
File 57="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Input.vi"
File 58="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure List.vi"
File 59="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Operating Mode.vi"
File 60="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Resistance List.vi"
File 61="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Resistance.vi"
File 62="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Slew Rate List.vi"
File 63="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Slew Rate.vi"
File 64="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Sweep.vi"
File 65="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Transient List.vi"
File 66="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Transient.vi"
File 67="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Trigger.vi"
File 68="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Voltage List.vi"
File 69="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure Voltage.vi"
File 70="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Configure/N33XX Configure.vi"
File 71="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Abort.vi"
File 72="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Initiate List.vi"
File 73="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Initiate Measurement.vi"
File 74="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Reset Input Protection.vi"
File 75="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Save Recall State.vi"
File 76="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Send Software Trigger.vi"
File 77="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/EasyIO/Action/N33XX Wait for Acquisition Complete.vi"
File 78="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Agilent N330X Series Readme.html"
File 79="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Agilent N330X Series.lvlib"
File 80="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Agilent N330X Series.lvproj"
File 81="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Close.vi"
File 82="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/dir.mnu"
File 83="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Initialize.vi"
File 84="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/VI Tree.vi"
File 85="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Utility/Error Query.vi"
File 86="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Utility/Reset.vi"
File 87="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Utility/Revision Query.vi"
File 88="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Utility/Self-Test.vi"
File 89="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Utility/Utility.mnu"
File 90="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Data.mnu"
File 91="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Current.vi"
File 92="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Instantaneous Current.vi"
File 93="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Instantaneous Power.vi"
File 94="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Instantaneous Voltage.vi"
File 95="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Power.vi"
File 96="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Read Measurement Voltage.vi"
File 97="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Abort.vi"
File 98="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Current.vi"
File 99="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Instantaneous Current.vi"
File 100="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Instantaneous Power.vi"
File 101="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Instantaneous Voltage.vi"
File 102="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Power.vi"
File 103="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Fetch Measurement Voltage.vi"
File 104="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Initiate Measurement.vi"
File 105="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Low Level Data.mnu"
File 106="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Send Software Trigger.vi"
File 107="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Data/Low Level Data/Wait for Acquisition Complete.vi"
File 108="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Channel.vi"
File 109="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Current List.vi"
File 110="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Current Protection.vi"
File 111="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Current.vi"
File 112="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Digital Port.vi"
File 113="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Input.vi"
File 114="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure List.vi"
File 115="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Operating Mode.vi"
File 116="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Resistance List.vi"
File 117="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Resistance.vi"
File 118="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Slew Rate List.vi"
File 119="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Slew Rate.vi"
File 120="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Sweep.vi"
File 121="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Transient List.vi"
File 122="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Transient.vi"
File 123="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Trigger.vi"
File 124="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Voltage List.vi"
File 125="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure Voltage.vi"
File 126="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Configure/Configure.mnu"
File 127="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Action-Status/Action-Status.mnu"
File 128="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Action-Status/Channel Status.vi"
File 129="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Action-Status/Initiate List.vi"
File 130="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Action-Status/Reset Input Protection.vi"
File 131="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Public/Action-Status/Save Recall State.vi"
File 132="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Private/Default Instrument Setup.vi"
File 133="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Examples/Agilent N330X Series Acquire Dwell Paced List Measurement.vi"
File 134="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Examples/Agilent N330X Series Acquire Instantaneous Measurement.vi"
File 135="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Examples/Agilent N330X Series Acquire Measurement.vi"
File 136="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Examples/Agilent N330X Series Acquire Triggered List Measurement.vi"
File 137="user.lib/_TI-LA/Instr Drivers/Electronic Load/N33XX/Driver/Base/Examples/Agilent N330X Series.bin3"


[File Group 1]
Target Dir="<menus>/Categories/TI-LabAutomation/Instrument Drivers/Electronic Load"
Replace Mode="Always"
Num Files=18
File 0="_functions_texas_instruments_lib_n33xx_1.mnu"
File 1="_functions_texas_instruments_lib_n33xx_10.mnu"
File 2="_functions_texas_instruments_lib_n33xx_11.mnu"
File 3="_functions_texas_instruments_lib_n33xx_12.mnu"
File 4="_functions_texas_instruments_lib_n33xx_13.mnu"
File 5="_functions_texas_instruments_lib_n33xx_14.mnu"
File 6="_functions_texas_instruments_lib_n33xx_15.mnu"
File 7="_functions_texas_instruments_lib_n33xx_16.mnu"
File 8="_functions_texas_instruments_lib_n33xx_17.mnu"
File 9="_functions_texas_instruments_lib_n33xx_2.mnu"
File 10="_functions_texas_instruments_lib_n33xx_3.mnu"
File 11="_functions_texas_instruments_lib_n33xx_4.mnu"
File 12="_functions_texas_instruments_lib_n33xx_5.mnu"
File 13="_functions_texas_instruments_lib_n33xx_6.mnu"
File 14="_functions_texas_instruments_lib_n33xx_7.mnu"
File 15="_functions_texas_instruments_lib_n33xx_8.mnu"
File 16="_functions_texas_instruments_lib_n33xx_9.mnu"
File 17="functions_texas_instruments_lib_n33xx.mnu"
